### PR TITLE
Pwa improvement

### PR DESCRIPTION
**Pull request by mhadaily**
Hi @yyx990803,

I have fixed the issues below and we can get 100/100 again 💯 

1.  Configured for a custom splash screen
2. The page contains a heading, skip link, or landmark region.
3. [user-scalable="no"] is not used in the <meta name="viewport"> element and the [maximum-scale] attribute is not less than 5.

Let me know if you need any other change, happy to help.

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks - not sure where (2) and (3) are specified for PWA, as I didn't see them listed in Lighthouse results. Do you have a link?

**Comment by mhadaily** [comment]
They are actually related to Accessibility not PWA itself. I just uploaded [here](http://vuehn.s3-website-us-west-1.amazonaws.com/vue-hn.now.sh_2017-05-30_07-37-47.html)

**Comment by yyx990803** [comment]
Oh I see, they are down below.

**Comment by rdunk** [comment]
Although the skip link might improve the lighthouse score, in this case the link just points to the entire app wrapper element so as far as I can see actually provides no accessibility benefits by skipping navigation elements for example. I know this app isn't focused on meeting accessibility requirements but thought I'd point this out in case anyone else was wondering about the functionality of that element.

**Pull request merged**
