### PR TITLE
minify html in production mode

### PR DESCRIPTION
**Pull request by eugenioclrc**
My two cents, the html rendered its now minified.

### CODE REVIEW

**Comment by crisbal** [comment]
I think there is no need to minify at runtime. The performance gain is negligible since everything gets gzipped anyway. This does also add some computation on the server.

**Comment by sirlancelot** [comment]
I wonder if this might be better implemented as a switch within the SSR plugin to tell it to simply not output whitespace to begin with?

**Comment by ram-you** [comment]
It affects the server response time

**Comment by yyx990803** [comment]
I think in this case the computation cost of the minification outweighs the gain. Although we may tune the SSR renderer to output more optimized markup by default.

**Pull request closed without merging**
